In [ ]:
# Siempre lo primero que debo hacer es importar pandas y numpy
import pandas as pd
import numpy as np

In [ ]:
#Ahora subimos el archivo desde google drive, ya no debemos logearnos de nuevo
df_estudiantes=pd.read_csv('/content/drive/MyDrive/StudentsPerformance (1).csv')
df_estudiantes

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
#Sigamos con la creaciÃ³n de columnas usando el metodo assign o el mÃ©todo insert
#Si quiero agregar varias columnas uso assign y tambien si quiero sobreescribir una columna

In [ ]:
#Fisica y filosofia aleatorias y las guardamos en variables
filosofia_scrore=np.random.randint(1, 100, size=1000)
fisica_score=np.random.randint(1, 100, size=1000)

In [ ]:
#Ahora le pondre un indice a cada fila para que sepa en donde va el dataframe
filosofia_nota=pd.Series(filosofia_scrore, index=np.arange(0,1000))
fisica_nota=pd.Series(fisica_score, index=np.arange (0,1000))

In [ ]:
#Ahora lo qe voy hacer es poner las nuevas columnas a mi dataframe, usando assign
df_estudiantes=df_estudiantes.assign(filosofia_scrore=filosofia_nota,fisica_score=fisica_nota)

In [ ]:
#Ahora vamos a usar el metodo insert, el metodo insert es diferente por que me permite especificar donde yo voy a colocar esa columna

# Al usar el metodo insert debemos tener cuidado po que no me devuelve copias si no que el cambia
df_estudiantes.insert(1, 'EDU_SCORE', fisica_nota)

In [ ]:
df_estudiantes

,gender,EDU_SCORE,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,filosofia_scrore,fisica_score
0,female,38,group B,bachelor's degree,standard,none,72,72,74,71,38
1,female,80,group C,some college,standard,completed,69,90,88,6,80
2,female,70,group B,master's degree,standard,none,90,95,93,46,70
3,male,53,group A,associate's degree,free/reduced,none,47,57,44,43,53
4,male,62,group C,some college,standard,none,76,78,75,37,62
...,...,...,...,...,...,...,...,...,...,...,...
995,female,17,group E,master's degree,standard,completed,88,99,95,34,17
996,male,90,group C,high school,free/reduced,none,62,55,55,8,90
997,female,82,group C,high school,free/reduced,completed,59,71,65,12,82
998,female,4,group D,some college,standard,completed,68,78,77,46,4
999,female,12,group D,some college,free/reduced,none,77,86,86,41,12